[2023-03-28 14:01:20,366] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: postgres_etl_dag.etl_from_radb 2023-03-28T14:01:17.999695+00:00 [queued]>
[2023-03-28 14:01:20,425] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: postgres_etl_dag.etl_from_radb 2023-03-28T14:01:17.999695+00:00 [queued]>
[2023-03-28 14:01:20,428] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2023-03-28 14:01:20,429] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2023-03-28 14:01:20,431] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2023-03-28 14:01:20,468] {taskinstance.py:1115} INFO - Executing <Task(PythonOperator): etl_from_radb> on 2023-03-28T14:01:17.999695+00:00
[2023-03-28 14:01:20,489] {standard_task_runner.py:52} INFO - Started process 3389 to run task
[2023-03-28 14:01:20,508] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'postgres_etl_dag', 'etl_from_radb', '2023-03-28T14:01:17.999695+00:00', '--job-id', '25', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ETL.py', '--cfg-path', '/tmp/tmpksrlri2_', '--error-file', '/tmp/tmpt_mw25f2']
[2023-03-28 14:01:20,523] {standard_task_runner.py:77} INFO - Job 25: Subtask etl_from_radb
[2023-03-28 14:01:20,643] {logging_mixin.py:109} INFO - Running <TaskInstance: postgres_etl_dag.etl_from_radb 2023-03-28T14:01:17.999695+00:00 [running]> on host 0bc3da97cebb
[2023-03-28 14:01:20,843] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=postgres_etl_dag
AIRFLOW_CTX_TASK_ID=etl_from_radb
AIRFLOW_CTX_EXECUTION_DATE=2023-03-28T14:01:17.999695+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-28T14:01:17.999695+00:00
[2023-03-28 14:01:21,045] {python.py:151} INFO - Done. Returned value was: None
[2023-03-28 14:01:21,095] {taskinstance.py:1219} INFO - Marking task as SUCCESS. dag_id=postgres_etl_dag, task_id=etl_from_radb, execution_date=20230328T140117, start_date=20230328T140120, end_date=20230328T140121
[2023-03-28 14:01:21,163] {local_task_job.py:151} INFO - Task exited with return code 0
[2023-03-28 14:01:21,214] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
